### PR TITLE
MAINT: stats.bws_test: adjustments to bws_test

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
scipy/scipy#18363

#### What does this implement/fix?
This makes recommended adjustments to the PR. There might be a few things I didn't catch, but this is what I'd suggest to merge this first PR.

### CODE REVIEW

**Comment by zhimin-z** [comment]
Why does it merge automatically? @mdhaber

**Comment by mdhaber** [comment]
I don't understand the question.

Do you mean that this happened automatically 
image

and was not intentional?

**Comment by zhimin-z** [comment]
> I don't understand the question.
> 
> Do you mean that this happened automatically image and was not intentional?
> 
> (If so, I would assume that it is because you have some sort of GitHub bots activated in your account. This would not be the first time that they have caused trouble.)
> 
> In any case, that merge needs to be reverted for this to work.

I am afraid so... Can you revert this operation? @mdhaber

**Comment by mdhaber** [comment]
Done. Do you plan to merge this? If so, please do not make any changes to your branch in the meantime.

**Comment by zhimin-z** [comment]
> Done. Do you plan to merge this? If so, please do not make any changes to your branch in the meantime.

This is not ready yet, since I am still playing around with the unit tests atm.

**Comment by mdhaber** [comment]
> This is not ready yet,

Do you mean that a) you are not ready to merge it or that b) the code is not ready to be merged? If b), what is the problem?
 
SciPy 1.11 is going to branch soon, so I would prefer to get this done since the PR has been open for about a month. Note that as a maintainer, I am able to make changes to PR branches myself (by default, unless you change the setting), so if I don't hear back, I'll go ahead and do that so we can get this in.

**Comment by zhimin-z** [comment]
> > This is not ready yet,
> 
> Do you mean that a) you are not ready to merge it or that b) the code is not ready to be merged? If b), what is the problem?
> 
> SciPy 1.11 is going to branch in about a week, so I would prefer to get this done since the PR has been open for about a month. Note that as a maintainer, I am able to make changes to PR branches myself (by default, unless you change the setting), so if I don't hear back, I'll go ahead and do that so we can get this in.

Thanks @mdhaber When do you plan for the release?  I hope to check all the unit testing before the release. Right now I noticed some of the custom test failed and have no time to look over in the last two weeks.

**Comment by mdhaber** [comment]
> Right now I noticed some of the custom test failed and have no time to look over in the last two weeks.

I will double-check, but I thought they passed locally. But I would suggest just going ahead and merging so that we can run this on CI. That will test all the major platforms, and that way I can debug.

> When do you plan for the release?

It is not up to me, but the plan is to branch SciPy 1.11.0 on May 29. If this hasn't merged by then, it will need to wait for SciPy 1.12.

**Comment by mdhaber** [comment]
As planned, I went ahead and merged this because the tests did indeed pass locally. In case you need your original branch, I backed it up at https://github.com/mdhaber/scipy/tree/bws-test-backup.

**Pull request merged**
